import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Box, CssBaseline } from "@mui/material";
import Sidebar from "@/components/sidebar/Sidebar";
import TopBar from "@/components/topbar/Topbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CssBaseline />
        <Box sx={{ display: "flex", height: "100vh" }}>
          <Sidebar />

          <Box
            component="main"
            sx={{
              flexGrow: 1,
              overflowY: "auto",
              bgcolor: "var(--background)",
            }}
          >
            <TopBar />
            <Box
              sx={{ width: "80%", margin: "auto", padding: "52px 3px 3px 3px" }}
            >
              {children}
            </Box>
          </Box>
        </Box>
      </body>
    </html>
  );
}
