import type { Metadata } from "next";
import localFont from "next/font/local";
import { Box, CssBaseline, Stack, StyledEngineProvider } from "@mui/material";
import Sidebar from "@/components/sidebar/Sidebar";
import TopBar from "@/components/topbar/Topbar";
import ThemeProviderWrapper from "@/components/theme/themeProvider";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProviderWrapper>
          <Box sx={{ display: "flex", height: "100vh" }}>
            <Sidebar />

            <Stack
              component="main"
              sx={{
                flexGrow: 1,
                overflowY: "auto",
                bgcolor: "var(--background)",
              }}
            >
              <TopBar />
              <Box
                sx={{
                  width: "80%",
                  height: "100vh",
                  margin: "auto",
                  padding: "52px 3px 3px 3px",
                }}
              >
                {children}
              </Box>
            </Stack>
          </Box>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
